apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167834125
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167834125
    app.kubernetes.io/part-of: test-app-167834125
  name: java-quarkus-167834125
  namespace: vuwyig23-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-167834125
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-167834125
    spec:
      containers:
      - image: quay.io/hacdev/build_service:GiV8i-java-quarkus-167834125
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
